FROM golang:1.22.0 AS builder

WORKDIR /app

RUN mkdir -p cmd/temperature_server
RUN mkdir -p internal/temperature_server/handler
RUN mkdir -p internal/temperature_server/model
RUN mkdir -p internal/temperature_server/repository
RUN mkdir -p internal/temperature_server/service
RUN mkdir -p pkg/utils

COPY go.mod ./
COPY go.sum ./

COPY cmd/temperature_server/main.go ./cmd/temperature_server
COPY internal/temperature_server/handler/weather.go ./internal/temperature_server/handler
COPY internal/temperature_server/model/address.go ./internal/temperature_server/model
COPY internal/temperature_server/model/coordinates.go ./internal/temperature_server/model
COPY internal/temperature_server/model/temperature.go ./internal/temperature_server/model
COPY internal/temperature_server/model/weather.go ./internal/temperature_server/model
COPY internal/temperature_server/repository/address.go ./internal/temperature_server/repository
COPY internal/temperature_server/repository/coordinates.go ./internal/temperature_server/repository
COPY internal/temperature_server/repository/weather_by_address.go ./internal/temperature_server/repository
COPY internal/temperature_server/repository/weather_by_coordinates.go ./internal/temperature_server/repository
COPY internal/temperature_server/service/weather.go ./internal/temperature_server/service
COPY pkg/utils/clean_string.go ./pkg/utils
COPY pkg/utils/is_number.go ./pkg/utils
COPY pkg/utils/number_converter.go ./pkg/utils
COPY pkg/utils/temperature_converter.go ./pkg/utils
COPY pkg/utils/env_var.go ./pkg/utils

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o service-b cmd/temperature_server/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/service-b ./

CMD ["./service-b"]
