version: "3"

services:
  service-a:
    build:
      context: .
      dockerfile: dockerfile.prod.input_server
    ports:
      - "3000:3000"
    environment:
      - SERVICE_URL=service-b
      - ZIPKIN_URL=zipkin
  service-b:
    build:
      context: .
      dockerfile: dockerfile.prod.temperature_server
    ports:
      - "8080:8080"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
