version: "3"

services:
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - .:/home/app
    ports:
      - "8080:8080"
      - "3000:3000"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  collector:
    image: otel/opentelemetry-collector
    container_name: collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "55681:55679"
    command: ["--config=/etc/otel-collector-config.yaml"]
