receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:55681"
exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
